# Generated by Django 4.2.20 on 2025-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_notificationsettings_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('customer_service', 'Customer Service'), ('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
