# Generated by Django 4.2.20 on 2025-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for the product', null=True),
        ),
    ]
