# Generated by Django 4.2.20 on 2025-05-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_message_options_remove_message_subject_and_more'),
        ('store', '0010_assign_conversations_to_messages'),
    ]

    operations = [
    ]
