# Generated by Django 4.2.20 on 2025-05-06 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def get_default_conversation():
    return 1 

class Migration(migrations.Migration):
    dependencies = [
        ('store', '0011_merge_20250506_1555'),
    ]
    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=get_default_conversation, to='store.Conversation', on_delete=models.CASCADE),
        ),
    ]