# Generated by Django 4.2.20 on 2025-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_wishlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('ewallet', 'E-Wallet'), ('cod', 'Cash on Delivery')], default='credit_card', max_length=30),
        ),
    ]
